robot_log_collector:
  ros__parameters:
    log_output_dir: "~/robot_log_collector/logs"
    file_prefix: "rosout"
    min_level: "INFO"
    max_file_size_mb: 50
    max_files: 20
    flush_every_n: 1
    flush_interval_ms: 1
    queue_capacity: 100000
    writer_batch_size: 2048
    include_logger_regex: ".*"
    exclude_logger_names: ["robot_log_collector"]
    stats_report_period_sec: 5
